import React from 'react';

import { BrowserRouter, HashRouter, Route, Router, Switch, Link } from 'react-router-dom'

import classnames from 'classnames/bind';

import moment from 'moment';

// Using CSS Modules so we assign the styles to a variable
import s from '../../css/App.styl';
const cx = classnames.bind(s);

import Toggle from 'react-toggle'

export default class EmailSettings extends React.Component {
  constructor(props, context) {
    super(props, context);

    this.state = {
      panelState: false
    }
  }
  componentDidMount(){

  }

  _togglePanel = () => {
    this.setState({
      panelState: !this.state.panelState
    })
  }

  render() {
    return (
      <div className={cx('changePassword')}>
        <div className={cx('changePasswordHeader')}>
          <div className={cx('changePasswordHeaderLeft')}>
            <div className={cx('changePasswordHeaderIcon')}>
              <img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAJ0SURBVFhH7ZZBS1RhGIWHWYQZooFKiBAmtJNC+w1iuyLa5DoRkaBfUEFUqLiwqE3uQhdFLQsxoyCtVbiwnQsRW2SZoqvSGZ9zPV7uhyN3ZhqDYB44fO89533fT3HkTqZKlVLJ5XId6CH6irasBTSGOtxWefL5fBcXvEQ56oIog1fogsfKh321LGpD19DM3hXRJfqNR1AnOmGpHkZbblPfDOpFbTzWem1x7K0IYdEquoea3XYAZegu+u6xALelw4I/GuCcRU8or6Iax6moVzOaRR+pteu343ToX/dQq62y0Q7tgnVb6TC0rAnOc7YCiI6RDaEViecH8hwH4J9H2rVkKx2aP3uo21YA/n3lSeQ5DsDvcT5nKx2aJz00YCsA/5vyJHgrjgPwB51P2EqH5jseemQrAP+H8iR4q44D8B+75batdBi6qAnOL7YC8EeilQnkOQ7An3de8M9ZEPpPMrCNdqgbbcfg6UM4rsWC+inHgQ8hfpN2oG3yetvFwdBbL79uKwC/V7lQbTuAqM/5tK3iYajfw+9tBeDfUi5U2w7QrPN+W8XDUB3a9IJO2zF4z5QJ1bZjNONsE9XZLg0GR73kta0YvE/KhGrbMZpxNmqrdJhvZMGGF12xHcHzT/lCte0Ini/b30BNtsuDBTe8bA2dtn0o9LSi6IfjvGm7fNiTZdE7L5zlOPTdroyeD+7VBzDr6O9gmf6f919QU+i4oxiiGvw37lHvKUeVgaXtaMkXzKEWR8pa0P57fxmddVRZWKyvaIu+6BcasNbsKTvj9qOBCxq46LkuTIL3gqPBbUcPl13iUn0dX1Bt+9/CxVnJj1X+RzKZXSNWw79BmIARAAAAAElFTkSuQmCC" />
            </div>
            <div className={cx('changePasswordHeaderTitle')}>
              <div className={cx('changePasswordHeaderTitleName')}>
                Two-factor authentication
              </div>
              <div className={cx('changePasswordHeaderTitleDescription')}>
                Log in using a code from your phone as well as a password
              </div>
            </div>
            <div className={cx('clear')}></div>
          </div>
          <div className={cx('changePasswordHeaderRight')}>
            <button onClick={() => this._togglePanel()}>
              {((this.state.panelState)  ? 'Close' : 'Edit')}
            </button>
          </div>
          <div className={cx('clear')}></div>
        </div>
        <div className={cx('changePasswordContent', ((this.state.panelState)  ? '' : 'hide'))}>
          <div>
            Set up Google Authenticator
          </div>
          <div>
            Install the Google Authenticator app
          </div>
          <div>
            <ul>
              <li>
                On your phone, go to the App Store specific to your mobile device
              </li>
              <li>
                Search for Google Authenticator
                (Download from )
              </li>
              <li>
                Download and install the application
              </li>
            </ul>
          </div>
          <div>
            Now open and configure Google Authenticator
          </div>
          <div>
            <ul>
              <li>
                In Google Authenticator, touch Menu and select "Set up account"
              </li>
              <li>
                Select "Scan a barcode"
              </li>
              <li>
                Use your phone's camera to scan this barcode
              </li>
            </ul>
            <div>
              QR
            </div>
            <div>
              Once you have scanned the barcode, enter the 6-digit verification code generated by the Authenticator app.
            </div>
            <div>
              Code: <input type="text" />
            </div>
            <div>
              <button>
                Verify and Save
              </button>
            </div>
          </div>
        </div>
      </div>
    );
  }
}
